server:
  port: 8020

spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/app20220916_2?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: dongmin
    password: dongmin1234
  jpa:
    hibernate:
      ddl-auto: create